### ISSUE TITLE
首次执行错误

### ISSUE THREAD

**Issue by kchen0x** [Rik-F5/xiaoya_db#47]
```
[INFO] 开始下载同步！
[INFO] python3 solid.py --media /media
2024-06-12 00:03:26 INFO *** xiaoya_emd version 1.3.4 ***
2024-06-12 00:03:27 INFO Picked: https://emby-data.f1rst.top/
2024-06-12 00:04:00 INFO There are 256796 files in https://emby-data.f1rst.top/
Traceback (most recent call last):
  File "/app/solid.py", line 556, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/solid.py", line 528, in main
    local_amount = await get_total_items_count(local_session)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/solid.py", line 315, in get_total_items_count
    async with conn.execute('SELECT COUNT(*) FROM files') as cursor:
  File "/usr/local/lib/python3.12/site-packages/aiosqlite/context.py", line 39, in __aenter__
    self._obj = await self._coro
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiosqlite/core.py", line 193, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiosqlite/core.py", line 132, in _execute
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiosqlite/core.py", line 115, in run
    result = function()
             ^^^^^^^^^^
sqlite3.OperationalError: no such table: files
[INFO] 运行完成！
[INFO] 等待43200秒后下次运行！
```

**Comment by kchen0x** [comment]
<img width="938" alt="image" src="https://github.com/Rik-F5/xiaoya_db/assets/9739009/eee60dac-0516-49a4-8339-0dcb0d1a59fb">

**Comment by kchen0x** [comment]
基本找到原因了。

说说我的情况：

1. Windows 10 物理硬盘，通过共享磁盘 CIFS 挂载到 Hyper-V 中的 Linux 虚拟机上 /data01。
2. /media 目录映射的是 /data01/xiaoya/xiaoya
3. xiaoya_emd 在初次启动创建数据库时和 CIFS 锁冲突，造成数据库锁。（发现这个问题是我直接在 Windows 上 clone 项目通过python执行是没有问题的，p.s. 需要先删除坏掉的 .localfiles.db 文件）
4. 关于 CIFS 的文件锁问题在这个帖子中也有涉及 https://forums.docker.com/t/sqlite-db-locked-when-on-a-windows-volume/13757 
5. 在 /etc/fstab 中添加 nolock 参数后重新挂载磁盘 `//server/share /mnt/mountpoint cifs username=your_username,password=your_password,iocharset=utf8,sec=ntlm,nolock 0 0
`
6. restart xiaoya_emd 恢复正常。

**Comment by Rik-F5** [comment]
非常感谢，之前发现数据库会在网络挂在的磁盘下出现锁死，一般建议是直接在物理盘的位置运行爬虫。

看来现在有解决办法了，我更新一下README

**Comment by kchen0x** [comment]
升级到最新内核之后，nolock 参数已经不再可用了，为了避免数据锁，可使用下列挂载参数：

`//server/share /mnt/mountpoint cifs username=your_username,password=your_password,iocharset=utf8,vers=3.0,nobrl,noperm 0 0`
